name = "matmailer"
main = "src/index.js"
compatibility_date = "2024-04-28"

[vars]
MAIL_DOMAIN = "ahmats.store"
ADMIN_NAME = "admin"
SESSION_EXPIRE_DAYS = "365"

[[d1_databases]]
binding = "DB"
database_name = "matmailer_db"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "matmailer-eml"

[[kv_namespaces]]
binding = "KV"

[assets]
directory = "public"
binding = "ASSETS"
