name = "matmailer"
main = "src/index.js"
compatibility_date = "2024-04-28"

[vars]
MAIL_DOMAIN = ""
JWT_TOKEN = ""
ADMIN_NAME = "admin"

[[d1_databases]]
binding = "DB"
database_name = "matmailer_db"
database_id = ""

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "matmailer-eml"

[[kv_namespaces]]
binding = "KV"
id = ""
